### ISSUE TITLE
Throwing the error

### ISSUE THREAD

**Issue by nadakumaran** [cyb3rzest/vasuki#1]
It will throw this error and then it shows the GO INSTALLED SUCCESSFULLY INSTALLING ALL DEPENDENCIES for long time

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/root/.zshrc: line 4: setopt: command not found
/root/.zshrc: line 6: setopt: command not found
/root/.zshrc: line 7: setopt: command not found
/root/.zshrc: line 8: setopt: command not found
/root/.zshrc: line 9: setopt: command not found
/root/.zshrc: line 10: setopt: command not found
/root/.zshrc: line 11: setopt: command not found
/root/.zshrc: line 19: bindkey: command not found
/root/.zshrc: line 20: bindkey: command not found
/root/.zshrc: line 21: bindkey: command not found
/root/.zshrc: line 22: bindkey: command not found
/root/.zshrc: line 23: bindkey: command not found
/root/.zshrc: line 24: bindkey: command not found
/root/.zshrc: line 25: bindkey: command not found
/root/.zshrc: line 26: bindkey: command not found
/root/.zshrc: line 27: bindkey: command not found
/root/.zshrc: line 28: bindkey: command not found
/root/.zshrc: line 29: bindkey: command not found
/root/.zshrc: line 30: bindkey: command not found
/root/.zshrc: line 33: autoload: command not found
/root/.zshrc: line 34: compinit: command not found
/root/.zshrc: line 35: zstyle: command not found
/root/.zshrc: line 36: zstyle: command not found
/root/.zshrc: line 37: zstyle: command not found
/root/.zshrc: line 38: zstyle: command not found
/root/.zshrc: line 39: zstyle: command not found
/root/.zshrc: line 40: zstyle: command not found
/root/.zshrc: line 41: zstyle: command not found
/root/.zshrc: line 42: zstyle: command not found
/root/.zshrc: line 43: zstyle: command not found
/root/.zshrc: line 44: zstyle: command not found
/root/.zshrc: line 45: zstyle: command not found
/root/.zshrc: line 46: zstyle: command not found
/root/.zshrc: line 47: zstyle: command not found
/root/.zshrc: line 53: setopt: command not found
/root/.zshrc: line 54: setopt: command not found
/root/.zshrc: line 55: setopt: command not found
/root/.zshrc: line 56: setopt: command not found
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 31: alias: -L: invalid option
alias: usage: alias [-p] [name[=value] ... ]
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 36: unalias: -m: invalid option
unalias: usage: unalias [-a] name [name ...]
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 39: 0=${(%):-%N}: bad substitution
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 42: /.version: No such file or directory
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 43: /.revision-hash: No such file or directory
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 58: autoload: command not found
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 59: is-at-least: command not found
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 143: syntax error near unexpected token `always'
/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh: line 143: `        } always {'
/root/.zshrc: line 169: ZSH_HIGHLIGHT_STYLES[bracket-level-2]: bad array subscript
/root/.zshrc: line 181: zle: command not found
/root/.zshrc: line 182: bindkey: command not found
/root/.zshrc: line 231: ${(s.:.)LS_COLORS}: bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 35:  ! ${+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 38:  ! ${+ZSH_AUTOSUGGEST_ORIGINAL_WIDGET_PREFIX} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 42:  ! ${+ZSH_AUTOSUGGEST_STRATEGY} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 45:  ! ${+ZSH_AUTOSUGGEST_CLEAR_WIDGETS} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 48:  ! ${+ZSH_AUTOSUGGEST_ACCEPT_WIDGETS} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 51:  ! ${+ZSH_AUTOSUGGEST_EXECUTE_WIDGETS} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 54:  ! ${+ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 57:  ! ${+ZSH_AUTOSUGGEST_IGNORE_WIDGETS} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 60:  ! ${+ZSH_AUTOSUGGEST_COMPLETIONS_PTY_NAME} : bad substitution
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: syntax error near unexpected token `('
/usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh: line 95: `              user:_zsh_autosuggest_(bound|orig)_*)'
/etc/zsh_command_not_found: line 8:  ! ${+functions[command_not_found_handler]} : bad substitution
cp: cannot stat '/root/go/pkg/mod/github.com/tomnomnom/gf@*/examples': No such file or directory

GO INSTALLED SUCCESSFULLY
INSTALLING ALL DEPENDENCIES

**Comment by cyb3rzest** [comment]
Issue in your `/root/.zshrc` file.
copy the `.zshrc` file from the normal user and paste that in `/root/` then run this command `source /root/.zshrc` 
after that, try again installing the same.

**Comment by nadakumaran** [comment]
Ok I will try

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
